title: Pose Plus
email: info@pose.plus
description: >- 
  Pose Plus is a free open source tool for gesture drawing. Make the most
  out of your image references with advanced features like auto zoom,
  collections, and more!
domain: pose.plus
url: https://pose.plus
twitter_username: CJSwitz
github_username:  CJSwitz

